# Generated by Django 5.2.9 on 2025-12-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_pro",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripe_customer_id",
        ),
    ]
