"""
Django settings for AulaKitPro_Core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os # Asegúrate de que esta línea esté al inicio del archivo, o añádela
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l=9_*19jnxav-7cm(n7y*&24g2b%x@oc*kpab_k=y8yv+*%6%('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # ⚠️ CAMBIA A False POR SEGURIDAD EN PRODUCCIÓN

ALLOWED_HOSTS = ['aulakitpro.iaasistentepersonal.com']


# Application definition

# AulaKitPro_Core/settings.py (Fragmento de INSTALLED_APPS)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Mis Apps
    'usuarios',  # <-- Debe tener una coma (,) aquí
    'pagos'     # <-- ESTE es el ÚLTIMO, NO lleva coma (,)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # <-- ¡Asegúrate de que esta línea esté!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # <-- ¡Asegúrate de que esta línea esté!
    'django.contrib.messages.middleware.MessageMiddleware', # <-- ¡Asegúrate de que esta línea esté!
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AulaKitPro_Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AulaKitPro_Core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AulaKitPro_Core/settings.py (Al final del archivo)

# Indica a Django que use el modelo de usuario personalizado de la app 'usuarios'
AUTH_USER_MODEL = 'usuarios.CustomUser'

# Redirección después de iniciar sesión
LOGIN_REDIRECT_URL = 'usuarios:dashboard'
# AulaKitPro_Core/settings.py (Al final del archivo)


# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# AulaKitPro_Core/settings.py (Al final del archivo, después de STATICFILES_DIRS)

# Directorio de recolección de archivos estáticos (para producción)
# Esto es necesario para evitar errores cuando se llama en urls.py
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# Configuraciones de Medios (Archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# AulaKitPro_Core/settings.py (Al final del archivo)

# ===============================================
# CONFIGURACIÓN DE STRIPE (Pasarela de Pago)
# ===============================================

STRIPE_PUBLISHABLE_KEY = 'pk_test_51LoEp2Ge9LhOzhJacVnZvE6Ir9NDNVQu61ygX1zofD7RwpWAEdVGFQcdrVSo9pPWr2EV1wp6d1ro9QEdq4YwMbU500Psnfoqye' 
STRIPE_SECRET_KEY = 'sk_test_51LoEp2Ge9LhOzhJaEkmmKKlANajkaUE5QsTKkgtGbJEy7ylO7TP88FMEwySLJEoPU6mjr29soMnmhhwUn14iqjoE00m69sSKS9' 

STRIPE_PRO_PRICE_ID = 'price_1SMILIGe9LhOzhJaBqXPLRAi'
# ⬇️ CLAVE SECRETA OBTENIDA DEL PANEL DE STRIPE
STRIPE_WEBHOOK_SECRET = 'whsec_Qxv8i7w10P2H0rpCofadS1xzVwtGkZNo'