# Generated by Django 5.0.6 on 2024-05-24 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField(default=False, verbose_name='Estado PRO')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Cliente en Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Suscripción en Stripe')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
